#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0
foamListTimes -rm
rm -rf pro*
rm -rf postP*
rm -rf log*
#------------------------------------------------------------------------------
